version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: hoge
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    image: golang:1.10.3
    environment:
      MYAPP_DATABASE_HOST: db
    command: "./bin/cleanarchitecture-sample-linux"
    volumes:
      - .:/go/src
    working_dir: /go/src
    ports:
      - "8080:8080"
    links:
      - db

volumes:
  db-data:
